#include "shaders/chunks.h"

uniform uint NB_PARTICLES;

layout(local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

void main()
{
    uint idx = gl_GlobalInvocationID.x;
    if (idx >= NB_PARTICLES)
        return;

    uint ci = pairs[idx].chunk_idx;

    if (ci >= c.nb_chunk_x * c.nb_chunk_y * c.nb_chunk_z)
        return;

    if (idx == 0u || ci != pairs[idx - 1u].chunk_idx)
    {
        start_chunks[ci] = idx;
    }
}
