#include "shaders/particle.glsl"

layout(std430, binding = BINDING_PREDICTED_POSITIONS) buffer PredictedPositionsBuffer
{
    vec2 predicted_positions[];
};
layout(std430, binding = BINDING_DENSITIES) buffer DensitiesBuffer
{
    float densities[];
};

uniform float dt;
uniform int NB_PARTICLES;

float particle_density(float d)
{
    float v = c.particle_influence_radius - d;

    if (v < 0)
        return 0;

    float vol = 6.0 / (3.14159265359 * c.particle_influence_radius * c.particle_influence_radius * c.particle_influence_radius * c.particle_influence_radius);

    return v * v * vol;
}

layout(local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

void main()
{
    uint idx = gl_GlobalInvocationID.x;
    if (idx >= NB_PARTICLES)
        return;

    float mass = 1.0f;
    float d = 0.0f;

    for (int i = 0; i < NB_PARTICLES; i++)
    {
        float dist = length(predicted_positions[idx] - predicted_positions[i]);
        d += particle_density(dist);
    }

    densities[idx] = d;
}
