#include "shaders/chunks.h"

uniform int NB_PARTICLES;

layout(std430, binding = BINDING_PREDICTED_POSITIONS) buffer PredictedPositionsBuffer
{
    vec3 predicted_positions[];
};

int particle_get_chunk_idx(vec3 pos)
{
    int cx = int(pos.x) / c.chunk_size;
    int cy = int(pos.y) / c.chunk_size;
    int cz = int(pos.z) / c.chunk_size;

    if (cx < 0)
        cx = 0;
    if (cy < 0)
        cy = 0;
    if (cz < 0)
        cz = 0;
    if (cx >= c.nb_chunk_x)
        cx = c.nb_chunk_x - 1;
    if (cy >= c.nb_chunk_y)
        cy = c.nb_chunk_y - 1;
    if (cz >= c.nb_chunk_z)
        cz = c.nb_chunk_z - 1;

    return cx + cy * c.nb_chunk_x * c.nb_chunk_z + cz * c.nb_chunk_x;
}

layout(local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

void main()
{
    uint idx = gl_GlobalInvocationID.x;
    if (idx >= NB_PARTICLES)
        return;

    pairs[idx].chunk_idx = particle_get_chunk_idx(predicted_positions[idx]);
    pairs[idx].particle_idx = int(idx);
}
