#include "shaders/particle.glsl"

uniform uint NB_PARTICLES;

layout(local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

void main()
{
    uint idx = gl_GlobalInvocationID.x;
    if (idx >= NB_PARTICLES)
        return;

    particles[idx].pos = vec3(float(c.sx) * fract(idx * 32361.3255389), float(c.sy) * fract(idx * 67289.217637), float(c.sz) * fract(idx * 3827.2321));
    particles[idx].velo = vec3(0.0);
    return;

    /*uint n = uint(ceil(pow(float(NB_PARTICLES), 1.0 / 3.0)));

    uint ix = idx % n;
    uint iz = (idx / n) % n;
    uint iy = idx / (n * n);

    float spacing = 2 * c.radius;

    float extent = float(n - 1u) * spacing;

    vec3 origin = center - 0.5 * vec3(extent, extent, extent);

    particles[idx].pos = origin + spacing * vec3(float(ix), float(iy), float(iz));
    particles[idx].velo = vec3(0.0);*/
}
