#include "shaders/particle.glsl"

layout(std430, binding = BINDING_PREDICTED_POSITIONS) buffer PredictedPositionsBuffer
{
    vec4 predicted_positions[];
};

uniform uint NB_PARTICLES;

layout(local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

void main()
{
    uint idx = gl_GlobalInvocationID.x;
    if (idx >= NB_PARTICLES)
        return;

    Particle p = particles[idx];

    p.velo.y -= 0.0981 * c.gravity_multiplier * s.dt;

    predicted_positions[idx] = vec4(p.pos + pow(c.velocity_drag, s.dt) * p.velo * s.dt, 0.0);

    particles[idx] = p;
}
