#include "shaders/particle.glsl"

layout(std430, binding = BINDING_PREDICTED_POSITIONS) buffer PredictedPositionsBuffer
{
    vec2 predicted_positions[];
};

layout(local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

void main()
{
    uint idx = gl_GlobalInvocationID.x;
    if (idx > predicted_positions.length())
        return;

    Particle p = particles[idx];

    p.velo.y += 0.0981 * c.gravity_multiplier;

    predicted_positions[idx] = p.pos + p.velo;

    particles[idx] = p;
}
