#include "shaders/chunks.h"
#include "shaders/particle.glsl"

layout(std430, binding = BINDING_PREDICTED_POSITIONS) buffer PredictedPositionsBuffer
{
    vec2 predicted_positions[];
};
layout(std430, binding = BINDING_DENSITIES) buffer DensitiesBuffer
{
    float densities[];
};

uniform int NB_PARTICLES;

float particle_compute_density_gradient(float dist)
{
    float slope = 2.0 * 6.0 / (3.14159265359 * c.particle_influence_radius * c.particle_influence_radius * c.particle_influence_radius * c.particle_influence_radius);

    return slope * (dist - c.particle_influence_radius);
}

vec2 particle_compute_pressure_other_particle(uint p1_index, uint p2_index)
{
    if (p1_index == p2_index)
        return vec2(0, 0);

    vec2 dir = predicted_positions[p1_index] - predicted_positions[p2_index];
    float dist = length(dir);

    if (dist < 0.00001 || dist > c.particle_influence_radius)
        return vec2(0, 0);

    float shared_density = (densities[p2_index] + densities[p1_index]) / 2;

    dir = dir * (1.0 / dist);

    float slope = particle_compute_density_gradient(dist);

    return dir * ((shared_density - c.target_pressure) * slope / densities[p2_index]);
}

vec2 particle_compute_pressure(uint idx)
{
    vec2 res = vec2(0, 0);

    vec2 pos = predicted_positions[idx];

    int radius = 1;

    int cx = (int(pos.x) / c.chunk_size < 0 ? 0 : int(pos.x) / c.chunk_size >= c.nb_chunk_x ? c.nb_chunk_x - 1 : int(pos.x) / c.chunk_size);
    int cy = (int(pos.y) / c.chunk_size < 0 ? 0 : int(pos.y) / c.chunk_size >= c.nb_chunk_y ? c.nb_chunk_y - 1 : int(pos.y) / c.chunk_size);

    for (int dx = -radius; dx <= radius; dx++)
        for (int dy = -radius; dy <= radius; dy++)
        {
            if (cx + dx < 0 || cy + dy < 0 || cx + dx >= c.nb_chunk_x || cy + dy >= c.nb_chunk_y)
                continue;

            uint nx = cx + dx;
            uint ny = cy + dy;
            uint start = start_chunks[nx + ny * c.nb_chunk_x];
			if (start >= NB_PARTICLES)
				continue;
            uint chunk_idx = pairs[start].chunk_idx;

            for (uint i = start; i < NB_PARTICLES && pairs[i].chunk_idx == chunk_idx; i++)
            {
                res += particle_compute_pressure_other_particle(idx, pairs[i].particle_idx);
            }
        }

    return res;
}

layout(local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

void main()
{
    uint i = gl_GlobalInvocationID.x;
    if (i >= NB_PARTICLES)
        return;

    Particle p = particles[i];

    vec2 grad = particle_compute_pressure(i);
    grad = -grad;

    grad *= c.pressure_force / densities[i];

    p.velo += grad;
    p.pos += p.velo;
    p.velo *= c.velocity_drag;

    if (p.pos.x > c.sx)
    {
        p.pos.x = c.sx - (p.pos.x - c.sx);
        p.velo.x *= -c.velocity_drag;
    }
    else if (p.pos.x < 0.0)
    {
        p.pos.x = -p.pos.x;
        p.velo.x *= -c.velocity_drag;
    }

    /*if (p.pos.y > c.sy)
    {
        p.pos.y = c.sy - (p.pos.y - c.sy);
        p.velo.y *= -c.velocity_drag;
    }
    else */
    if (p.pos.y < 0)
    {
        p.pos.y *= -1.0;
        p.velo.y *= -c.velocity_drag;
    }

    particles[i] = p;
}
