#include "shaders/chunks.h"
#include "shaders/particle.glsl"

layout(std430, binding = BINDING_PREDICTED_POSITIONS) buffer PredictedPositionsBuffer
{
    vec3 predicted_positions[];
};
layout(std430, binding = BINDING_DENSITIES) buffer DensitiesBuffer
{
    float densities[];
};

uniform int NB_PARTICLES;

float particle_compute_density_gradient(float dist)
{
    float v = c.particle_influence_radius - dist;

    if (v < 0)
        return 0;

    float scale = 15.0 / (pow(c.particle_influence_radius, 5) * 3.14159265359);

    return -v * scale;
}

vec3 particle_compute_pressure_other_particle(uint p1_index, uint p2_index)
{
    if (p1_index == p2_index)
        return vec3(0, 0, 0);

    vec3 dir = predicted_positions[p1_index] - predicted_positions[p2_index];
    float dist = length(dir);

    if (dist < 0.00001 || dist > c.particle_influence_radius || densities[p2_index] < 0.00001)
        return vec3(0, 0, 0);

    float shared_density = (densities[p2_index] + densities[p1_index]) / 2;

    dir = dir * (1.0 / dist);

    float slope = particle_compute_density_gradient(dist);

    return dir * ((shared_density - c.target_pressure) * slope / densities[p2_index]);
}

vec3 particle_compute_pressure(uint idx)
{
    vec3 res = vec3(0, 0, 0);

    vec3 pos = predicted_positions[idx];

    int radius = 1;

    int cx = (int(pos.x) / c.chunk_size < 0 ? 0 : int(pos.x) / c.chunk_size >= c.nb_chunk_x ? c.nb_chunk_x - 1 : int(pos.x) / c.chunk_size);
    int cy = (int(pos.y) / c.chunk_size < 0 ? 0 : int(pos.y) / c.chunk_size >= c.nb_chunk_y ? c.nb_chunk_y - 1 : int(pos.y) / c.chunk_size);
    int cz = (int(pos.z) / c.chunk_size < 0 ? 0 : int(pos.z) / c.chunk_size >= c.nb_chunk_z ? c.nb_chunk_z - 1 : int(pos.z) / c.chunk_size);

    for (int dx = -radius; dx <= radius; dx++)
        for (int dy = -radius; dy <= radius; dy++)
            for (int dz = -radius; dz <= radius; dz++)
            {
                int nx = cx + dx;
                int ny = cy + dy;
                int nz = cz + dz;

                if (nx < 0 || ny < 0 || nz < 0 || nx >= c.nb_chunk_x || ny >= c.nb_chunk_y || nz >= c.nb_chunk_z)
                    continue;

                int start = start_chunks[nx + ny * c.nb_chunk_x * c.nb_chunk_z + nz * c.nb_chunk_x];
                if (start == -1 || start >= NB_PARTICLES)
                    continue;
                uint chunk_idx = pairs[start].chunk_idx;

                for (uint i = start; i < NB_PARTICLES && pairs[i].chunk_idx == chunk_idx; i++)
                {
                    res += particle_compute_pressure_other_particle(idx, pairs[i].particle_idx);
                }
            }

    return res;
}

layout(local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

void main()
{
    uint i = gl_GlobalInvocationID.x;
    if (i >= NB_PARTICLES)
        return;

    vec3 grad = particle_compute_pressure(i);
    grad = -grad;

    grad *= c.pressure_force / densities[i];

    particles[i].velo += grad * s.dt;
}
