#include "shaders/particle.glsl"

/*layout(std430, binding = BINDING_PREDICTED_POSITIONS) buffer PredictedPositionsBuffer
{
    vec2 predicted_positions[];
};
layout(std430, binding = BINDING_DENSITIES) buffer DensitiesBuffer
{
    float densities[];
};*/

uniform int NB_PARTICLES;

/*float particle_compute_density_gradient(float dist)
{
    float slope = 2.0 * 6.0 / (3.14159265359 * c.particle_influence_radius * c.particle_influence_radius * c.particle_influence_radius * c.particle_influence_radius);

    return slope * (dist - c.particle_influence_radius);
}

vec2 particle_compute_pressure_other_particle(uint p1_index, uint p2_index)
{
    if (p1_index == p2_index)
        return vec2(0, 0);

    vec2 dir = predicted_positions[p1_index] - predicted_positions[p2_index];
    float dist = length(dir);

    if (dist < 0.00001 || dist > c.particle_influence_radius)
        return vec2(0, 0);

    float density = (densities[p2_index] + densities[p1_index]) / 2;
    if (density < 0.00001)
        return vec2(0, 0);

    dir = dir * (1.0 / dist);

    float slope = particle_compute_density_gradient(dist);

    return dir * ((density - c.target_pressure) * slope / density);
}

vec2 particle_compute_pressure(uint i)
{
    vec2 res = vec2(0, 0);

    for (uint j = 0; j < NB_PARTICLES; j++)
    {
        res += particle_compute_pressure_other_particle(i, j);
    }

    return res;
}*/

layout(local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

void main()
{
    uint i = gl_GlobalInvocationID.x;
    /*if (i >= NB_PARTICLES)
        return;*/

    Particle p = particles[i];
    p.pos += vec2(1, 0);
    particles[i] = p;
    return;

    /*vec2 grad = particle_compute_pressure(i);
    grad = -grad;

    //grad *= c.pressure_force / densities[i];

    p.velo += grad;
    p.velo += vec2(1, 0);
    p.pos += p.velo;
    particles[i] = p;
    //p.velo *= c.velocity_drag;

    if (p.pos.x > 1920.0)
    {
        p.pos.x = 1920;
        p.velo.x *= -0.9;
    }
    else if (p.pos.x < 0.0)
    {
        p.pos.x = -p.pos.x;
        p.velo.x *= -0.9;
    }

    if (p.pos.y > 1080.0)
    {
        p.pos.y = 1080;
        p.velo.y *= -0.9;
    }
    else if (p.pos.y < 0.0)
    {
        p.pos.y *= -1.0;
        p.velo.y *= -0.9;
    }

    particles[i] = p;

    return;

    float rad = 5;

    for (int i2 = 0; i2 < 100; i2++)
    {
        if (i2 < i)
            continue;

        vec2 dir = particles[i].pos - particles[i2].pos;
        float dist = length(dir);

        if (dist < 2 * rad && dist > 0.0001)
        {
            float d = dot(particles[i].velo - particles[i2].velo, dir);

            if (d < 0)
            {
                vec2 v_diff = dir * d / dist;

                particles[i].velo -= v_diff;
                particles[i2].velo += v_diff;
            }

            vec2 d2 = dir * (2.0 * rad - dist) / dist;

            particles[i].pos += d2 * 0.5;
            particles[i2].pos -= d2 * 0.5;
        }
    }

    particles[i] = p;*/
}
