struct Particle
{
    vec2 pos;
    vec2 velo;
};

layout(std430, binding = 0) buffer ParticleBuffer
{
    Particle particles[];
};

layout(std430, binding = BINDING_DENSITIES) buffer DensitiesBuffer
{
    float densities[];
};

uniform float dt;
uniform int N;

void main()
{
    uint i = gl_GlobalInvocationID.x;
    if (i >= particles.length())
        return;

    Particle p = particles[i];

    p.pos += p.velo * dt;

    if (p.pos.x > 1920.0)
    {
        p.pos.x = 1920;
        p.velo.x *= -0.9;
    }
    else if (p.pos.x < 0.0)
    {
        p.pos.x = -p.pos.x;
        p.velo.x *= -0.9;
    }

    if (p.pos.y > 1080.0)
    {
        p.pos.y = 1080;
        p.velo.y *= -0.9;
    }
    else if (p.pos.y < 0.0)
    {
        p.pos.y *= -1.0;
        p.velo.y *= -0.9;
    }

    for (int i2 = 0; i2 < N; i2++)
    {
        //densities
    }

    particles[i] = p;

    return;

    float rad = 5;

    for (int i2 = 0; i2 < 100; i2++)
    {
        if (i2 < i)
            continue;

        vec2 dir = particles[i].pos - particles[i2].pos;
        float dist = length(dir);

        if (dist < 2 * rad && dist > 0.0001)
        {
            float d = dot(particles[i].velo - particles[i2].velo, dir);

            if (d < 0)
            {
                vec2 v_diff = dir * d / dist;

                particles[i].velo -= v_diff;
                particles[i2].velo += v_diff;
            }

            vec2 d2 = dir * (2.0 * rad - dist) / dist;

            particles[i].pos += d2 * 0.5;
            particles[i2].pos -= d2 * 0.5;
        }
    }

    particles[i] = p;
}
