#include "shaders/particle.glsl"
#include "shaders/chunks.h"

uniform int NB_PARTICLES;

layout(std430, binding = BINDING_PREDICTED_POSITIONS) buffer PredictedPositionsBuffer
{
    vec3 predicted_positions[];
};

layout(local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

float viscosityKernel(float d)
{
	if (d > c.particle_influence_radius)
		return 0;

    float scale = 315.0 / (64.0 * 3.14159265359 * pow(abs(c.particle_influence_radius), 9));
    float v = c.particle_influence_radius * c.particle_influence_radius - d * d;

	return v * v * v  * scale;
}

vec3 particle_calculate_viscosity(uint idx, uint i)
{
    float dist = length(predicted_positions[idx] - predicted_positions[i]);
    return viscosityKernel(dist) * (particles[i].velo - particles[idx].velo);
}

void main()
{
    uint idx = gl_GlobalInvocationID.x;
    if (idx >= NB_PARTICLES)
        return;

    Particle p = particles[idx];

    vec3 res = vec3(0, 0, 0);
    vec3 pos = predicted_positions[idx];

    int radius = 1;

    int cx = clamp(int(floor(pos.x / c.chunk_size)), 0, c.nb_chunk_x - 1);
    int cy = clamp(int(floor(pos.y / c.chunk_size)), 0, c.nb_chunk_y - 1);
    int cz = clamp(int(floor(pos.z / c.chunk_size)), 0, c.nb_chunk_z - 1);

    for (int dx = -radius; dx <= radius; dx++)
        for (int dy = -radius; dy <= radius; dy++)
            for (int dz = -radius; dz <= radius; dz++)
            {
                int nx = cx + dx;
                int ny = cy + dy;
                int nz = cz + dz;

                if (nx < 0 || ny < 0 || nz < 0 || nx >= c.nb_chunk_x || ny >= c.nb_chunk_y || nz >= c.nb_chunk_z)
                    continue;

                uint start = start_chunks[nx + ny * c.nb_chunk_x * c.nb_chunk_z + nz * c.nb_chunk_x];
                if (start == -1 || start >= NB_PARTICLES)
                    continue;
                uint chunk_idx = pairs[start].chunk_idx;

                for (uint i = start; i < NB_PARTICLES && pairs[i].chunk_idx == chunk_idx; i++)
                {
                    res += particle_calculate_viscosity(idx, pairs[i].particle_idx);
                }
            }

    p.velo += c.viscosity_strength * res * s.dt;

    particles[idx] = p;

}
