#define BINDING_PARTICLES 0
#define BINDING_DENSITIES 1
#define BINDING_PREDICTED_POSITIONS 2
#define BINDING_CONFIG 3
#define BINDING_START_CHUNKS 4
#define BINDING_END_CHUNKS 5
#define BINDING_PAIRS 6
#define BINDING_SORTED_PAIRS 7
#define BINDING_HISTOGRAM 8


